# Generated by Django 2.0.8 on 2018-08-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEA', '0002_projects_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='khushi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
