# Generated by Django 2.0.8 on 2018-08-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MEA', '0003_khushi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='khushi',
        ),
    ]
