# Generated by Django 2.0.8 on 2018-08-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEA', '0004_delete_khushi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Non-Technical', 'Non-Technical')], max_length=30),
        ),
    ]
