# Generated by Django 2.0.8 on 2018-08-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEA', '0005_auto_20180831_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct',
            field=models.CharField(max_length=200),
        ),
    ]
